import { useState } from "react";
import { Category, Product } from "../types";
import { money, storage } from "../lib/storage";

interface Props { products: Product[]; setProducts: (products: Product[]) => void; }
const emptyProduct: Omit<Product, "id"> = { name: "", barcode: "", category: "bebidas", price: 0, stock: 0, minStock: 5 };

export default function Produtos({ products, setProducts }: Props) {
  const [form, setForm] = useState(emptyProduct); const [editingId, setEditingId] = useState<string | null>(null); const [search, setSearch] = useState("");
  const filtered = products.filter((p) => p.name.toLowerCase().includes(search.toLowerCase()) || p.barcode.includes(search));
  function saveProduct(e: React.FormEvent) { e.preventDefault(); if (!form.name || !form.barcode) return; const updated = editingId ? products.map((p) => p.id === editingId ? { ...form, id: editingId } : p) : [...products, { ...form, id: crypto.randomUUID() }]; setProducts(updated); storage.saveProducts(updated); setForm(emptyProduct); setEditingId(null); }
  function editProduct(product: Product) { setEditingId(product.id); setForm({ name: product.name, barcode: product.barcode, category: product.category, price: product.price, stock: product.stock, minStock: product.minStock }); }
  function deleteProduct(id: string) { if (!confirm("Deseja excluir este produto?")) return; const updated = products.filter((p) => p.id !== id); setProducts(updated); storage.saveProducts(updated); }
  return <section className="grid lg:grid-cols-[0.8fr_1.2fr] gap-6"><form onSubmit={saveProduct} className="card"><h2 className="text-2xl font-black mb-4">{editingId ? "Editar produto" : "Cadastrar produto"}</h2><input placeholder="Nome do produto" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="input" /><input placeholder="Código de barras" value={form.barcode} onChange={(e) => setForm({ ...form, barcode: e.target.value })} className="input" /><select value={form.category} onChange={(e) => setForm({ ...form, category: e.target.value as Category })} className="input"><option value="bebidas">Bebidas</option><option value="suplementos">Suplementos</option><option value="uniformes">Uniformes</option><option value="acessorios">Acessórios</option><option value="outros">Outros</option></select><input type="number" step="0.01" placeholder="Preço" value={form.price} onChange={(e) => setForm({ ...form, price: Number(e.target.value) })} className="input" /><input type="number" placeholder="Estoque" value={form.stock} onChange={(e) => setForm({ ...form, stock: Number(e.target.value) })} className="input" /><input type="number" placeholder="Estoque mínimo" value={form.minStock} onChange={(e) => setForm({ ...form, minStock: Number(e.target.value) })} className="input" /><button className="w-full btn-primary">{editingId ? "Salvar alteração" : "Cadastrar produto"}</button>{editingId && <button type="button" onClick={() => { setEditingId(null); setForm(emptyProduct); }} className="w-full mt-3 bg-slate-200 rounded-2xl py-3 font-bold">Cancelar</button>}</form><div className="card"><h2 className="text-2xl font-black mb-4">Produtos da academia</h2><input placeholder="Buscar por nome ou código" value={search} onChange={(e) => setSearch(e.target.value)} className="input" /><div className="overflow-x-auto"><table className="w-full text-left border-separate border-spacing-y-2"><thead><tr className="text-slate-500 text-sm"><th>Produto</th><th>Código</th><th>Categoria</th><th>Preço</th><th>Estoque</th><th>Ações</th></tr></thead><tbody>{filtered.map((product) => <tr key={product.id} className="bg-slate-50"><td className="p-3 rounded-l-xl font-bold">{product.name}</td><td className="p-3">{product.barcode}</td><td className="p-3 capitalize">{product.category}</td><td className="p-3">{money(product.price)}</td><td className="p-3"><span className={`badge ${product.stock <= product.minStock ? "bg-red-100 text-red-700" : "bg-emerald-100 text-emerald-700"}`}>{product.stock}</span></td><td className="p-3 rounded-r-xl"><div className="flex gap-2"><button onClick={() => editProduct(product)} className="btn-light">Editar</button><button onClick={() => deleteProduct(product.id)} className="btn-danger">Excluir</button></div></td></tr>)}{filtered.length === 0 && <tr><td colSpan={6} className="text-center py-8 text-slate-500">Nenhum produto encontrado.</td></tr>}</tbody></table></div></div></section>;
}
