import { Product, Sale } from "../types";
import { money } from "../lib/storage";

interface Props { sales: Sale[]; products: Product[]; }
export default function Relatorios({ sales, products }: Props) {
  const today = new Date().toISOString().slice(0, 10); const month = new Date().toISOString().slice(0, 7);
  const totalToday = sales.filter((s) => s.date.slice(0, 10) === today).reduce((sum, s) => sum + s.total, 0);
  const totalMonth = sales.filter((s) => s.date.slice(0, 7) === month).reduce((sum, s) => sum + s.total, 0);
  const paymentTotals = { dinheiro: sales.filter((s) => s.paymentMethod === "dinheiro").reduce((sum, s) => sum + s.total, 0), cartão: sales.filter((s) => s.paymentMethod === "cartão").reduce((sum, s) => sum + s.total, 0), pix: sales.filter((s) => s.paymentMethod === "pix").reduce((sum, s) => sum + s.total, 0) };
  const productSales: Record<string, number> = {}; sales.forEach((sale) => sale.items.forEach((item) => productSales[item.name] = (productSales[item.name] || 0) + item.quantity));
  const mostSold = Object.entries(productSales).map(([name, quantity]) => ({ name, quantity })).sort((a, b) => b.quantity - a.quantity);
  return <section className="space-y-6"><div className="grid md:grid-cols-4 gap-4"><Card title="Vendido hoje" value={money(totalToday)} /><Card title="Vendido no mês" value={money(totalMonth)} /><Card title="Total de vendas" value={String(sales.length)} /><Card title="Itens em estoque" value={String(products.reduce((sum, p) => sum + p.stock, 0))} /></div><div className="grid lg:grid-cols-2 gap-6"><div className="card"><h2 className="text-2xl font-black mb-4">Mais vendidos na academia</h2><div className="space-y-3">{mostSold.map((item, index) => <div key={item.name} className="flex justify-between bg-slate-50 rounded-2xl p-4"><span>#{index + 1} {item.name}</span><strong>{item.quantity} un.</strong></div>)}{mostSold.length === 0 && <p className="text-slate-500">Nenhuma venda realizada ainda.</p>}</div></div><div className="card"><h2 className="text-2xl font-black mb-4">Vendas por pagamento</h2><PaymentRow label="Dinheiro" value={paymentTotals.dinheiro} /><PaymentRow label="Cartão" value={paymentTotals.cartão} /><PaymentRow label="Pix" value={paymentTotals.pix} /></div></div><div className="card"><h2 className="text-2xl font-black mb-4">Estoque atual</h2><div className="overflow-x-auto"><table className="w-full text-left border-separate border-spacing-y-2"><thead><tr className="text-slate-500 text-sm"><th>Produto</th><th>Categoria</th><th>Preço</th><th>Estoque</th><th>Situação</th></tr></thead><tbody>{products.map((p) => <tr key={p.id} className="bg-slate-50"><td className="p-3 rounded-l-xl font-bold">{p.name}</td><td className="p-3 capitalize">{p.category}</td><td className="p-3">{money(p.price)}</td><td className="p-3">{p.stock}</td><td className="p-3 rounded-r-xl">{p.stock <= p.minStock ? <span className="badge bg-red-100 text-red-700">Estoque baixo</span> : <span className="badge bg-emerald-100 text-emerald-700">Normal</span>}</td></tr>)}</tbody></table></div></div></section>;
}
function Card({ title, value }: { title: string; value: string }) { return <div className="card"><p className="text-slate-500 font-bold">{title}</p><strong className="text-3xl font-black">{value}</strong></div>; }
function PaymentRow({ label, value }: { label: string; value: number }) { return <div className="flex justify-between bg-slate-50 rounded-2xl p-4 mb-3"><span>{label}</span><strong>{money(value)}</strong></div>; }
