import { useState } from "react";
import { Member, PlanType } from "../types";
import { checkMemberStatus, storage } from "../lib/storage";

interface Props { members: Member[]; setMembers: (members: Member[]) => void; }
const emptyMember: Omit<Member, "id" | "status"> = { name: "", cpf: "", registration: "", phone: "", belt: "Faixa Branca", planType: "mensal", dueDate: new Date().toISOString().slice(0, 10) };

export default function Socios({ members, setMembers }: Props) {
  const [form, setForm] = useState(emptyMember); const [editingId, setEditingId] = useState<string | null>(null); const [search, setSearch] = useState("");
  const normalized = members.map((m) => ({ ...m, status: checkMemberStatus(m.dueDate, m.status) }));
  const filtered = normalized.filter((m) => m.name.toLowerCase().includes(search.toLowerCase()) || m.cpf.includes(search) || m.registration.toLowerCase().includes(search.toLowerCase()) || m.belt.toLowerCase().includes(search.toLowerCase()));
  function saveMember(e: React.FormEvent) { e.preventDefault(); if (!form.name || !form.cpf || !form.registration) return; const status = checkMemberStatus(form.dueDate, "ativo"); const updated = editingId ? members.map((m) => m.id === editingId ? { ...form, id: editingId, status } : m) : [...members, { ...form, id: crypto.randomUUID(), status }]; setMembers(updated); storage.saveMembers(updated); setForm(emptyMember); setEditingId(null); }
  function editMember(member: Member) { setEditingId(member.id); setForm({ name: member.name, cpf: member.cpf, registration: member.registration, phone: member.phone, belt: member.belt, planType: member.planType, dueDate: member.dueDate }); }
  function deleteMember(id: string) { if (!confirm("Deseja excluir este aluno?")) return; const updated = members.filter((m) => m.id !== id); setMembers(updated); storage.saveMembers(updated); }
  return <section className="grid lg:grid-cols-[0.8fr_1.2fr] gap-6"><form onSubmit={saveMember} className="card"><h2 className="text-2xl font-black mb-4">{editingId ? "Editar aluno" : "Cadastrar aluno"}</h2><input placeholder="Nome do aluno" value={form.name} onChange={(e) => setForm({ ...form, name: e.target.value })} className="input" /><input placeholder="CPF" value={form.cpf} onChange={(e) => setForm({ ...form, cpf: e.target.value })} className="input" /><input placeholder="Matrícula" value={form.registration} onChange={(e) => setForm({ ...form, registration: e.target.value })} className="input" /><input placeholder="Telefone" value={form.phone} onChange={(e) => setForm({ ...form, phone: e.target.value })} className="input" /><select value={form.belt} onChange={(e) => setForm({ ...form, belt: e.target.value })} className="input"><option>Faixa Branca</option><option>Faixa Azul</option><option>Faixa Roxa</option><option>Faixa Marrom</option><option>Faixa Preta</option></select><select value={form.planType} onChange={(e) => setForm({ ...form, planType: e.target.value as PlanType })} className="input"><option value="mensal">Mensal</option><option value="trimestral">Trimestral</option><option value="semestral">Semestral</option><option value="anual">Anual</option></select><input type="date" value={form.dueDate} onChange={(e) => setForm({ ...form, dueDate: e.target.value })} className="input" /><button className="w-full btn-primary">{editingId ? "Salvar aluno" : "Cadastrar aluno"}</button></form><div className="card"><h2 className="text-2xl font-black mb-4">Alunos / Sócios</h2><input placeholder="Buscar por nome, CPF, matrícula ou faixa" value={search} onChange={(e) => setSearch(e.target.value)} className="input" /><div className="overflow-x-auto"><table className="w-full text-left border-separate border-spacing-y-2"><thead><tr className="text-slate-500 text-sm"><th>Aluno</th><th>Faixa</th><th>Matrícula</th><th>Plano</th><th>Vencimento</th><th>Status</th><th>Ações</th></tr></thead><tbody>{filtered.map((m) => <tr key={m.id} className="bg-slate-50"><td className="p-3 rounded-l-xl font-bold">{m.name}</td><td className="p-3">{m.belt}</td><td className="p-3">{m.registration}</td><td className="p-3 capitalize">{m.planType}</td><td className="p-3">{m.dueDate}</td><td className="p-3"><span className={`badge ${m.status === "ativo" ? "bg-emerald-100 text-emerald-700" : m.status === "vencido" ? "bg-red-100 text-red-700" : "bg-slate-200 text-slate-700"}`}>{m.status}</span></td><td className="p-3 rounded-r-xl"><div className="flex gap-2"><button onClick={() => editMember(m)} className="btn-light">Editar</button><button onClick={() => deleteMember(m.id)} className="btn-danger">Excluir</button></div></td></tr>)}{filtered.length === 0 && <tr><td colSpan={7} className="text-center py-8 text-slate-500">Nenhum aluno encontrado.</td></tr>}</tbody></table></div></div></section>;
}
